fix the parsing of addr
aquasecurity/tracee pull request #1261
Opened 2021-12-15 17:07 UTC by AsafEitani

fix #1260

2021-12-16 14:19 UTC, danielpacak requested changes

2022-01-16 10:18 UTC, roikol commented on signatures/golang/stdio_over_socket.go
> +		stringInterMap, isStringInterMap := arg.Value.(map[string]interface{})
hey,
this happens when using output option format:json. 
with format:gob the Value is `map[string]string` as expected.

2022-01-16 11:04 UTC, yanivagman commented on signatures/golang/stdio_over_socket.go
> +		stringInterMap, isStringInterMap := arg.Value.(map[string]interface{})
If that's the case, the bug is that we have different outputs for json and gob formats, isn't it?

2022-01-16 12:11 UTC, roikol commented on signatures/golang/stdio_over_socket.go
> +		stringInterMap, isStringInterMap := arg.Value.(map[string]interface{})
yes it is

2022-01-16 12:25 UTC, yanivagman commented on signatures/golang/stdio_over_socket.go
> +		stringInterMap, isStringInterMap := arg.Value.(map[string]interface{})
So I think this is not the correct place to have the fix.
We should find the cause for the difference and handle it instead

2022-01-16 12:27 UTC, yanivagman commented on signatures/golang/stdio_over_socket.go
> +		stringInterMap, isStringInterMap := arg.Value.(map[string]interface{})
@itaysk can it be related to #988 or something similar?

2022-01-24 17:50 UTC, danielpacak commented on signatures/golang/stdio_over_socket.go
> +		stringInterMap, isStringInterMap := arg.Value.(map[string]interface{})
I'm not sure what is the goal of #988 but I had a look into code and basically GOB encodes and decodes `map[string]string` without loosing type information of map values. However, JSON unmarshaller decodes to `map[string]interface{}` and loose type information.

We can maybe patch it in existing, custom `UnmarshalJSON` callback, but I'm wondering if that's the only corner case to handle to keep the signature implementation agnostic of data serialisation format. WDYT?

```go
// UnmarshalJSON implements the json.Unmarshaler interface.
func (arg *Argument) UnmarshalJSON(b []byte) error {
	type argument Argument //alias Argument so we can unmarshal it within the unmarshaler implementation
	d := json.NewDecoder(bytes.NewReader(b))
	d.UseNumber()
	if err := d.Decode((*argument)(arg)); err != nil {
		return err
	}
	if arg.Value == nil {
		return nil
	}
	// Workaround to keep signature handler agnostic of GOB or JSON serialisation format
	if v, ok := arg.Value.(map[string]interface{}); ok && len(v) > 0 {
		mapWithStringValues := make(map[string]string, len(v))
		for key, value := range v {
			if stringValue, ok := value.(string); ok {
				mapWithStringValues[key] = stringValue
			}
		}
		arg.Value = mapWithStringValues
	}
```

2022-03-09 16:39 UTC, yanivagman commented
most likely related to #988

2022-04-13 21:04 UTC, simar7 commented
Data point: Just loaded a fresh Tracee and I think the issue is still there.
```
tracee@e568d7d2e632[/tracee]$ sudo ./dist/tracee-ebpf \
  -o format:json \
  -o option:parse-arguments \
  --trace comm=bash \
  --trace follow \
  --trace event!='sched*' | \
  ./dist/tracee-rules \
  --input-tracee file:stdin \
  --input-tracee format:json
Loaded 14 signature(s): [TRC-1 TRC-13 TRC-2 TRC-14 TRC-3 TRC-11 TRC-9 TRC-4 TRC-5 TRC-12 TRC-8 TRC-6 TRC-10 TRC-7]
2022/04/13 21:01:31 error handling event by signature Standard Input/Output Over Socket: couldn't convert arg to addr
2022/04/13 21:01:31 error handling event by signature Standard Input/Output Over Socket: couldn't convert arg to addr
2022/04/13 21:01:31 error handling event by signature Standard Input/Output Over Socket: couldn't convert arg to addr
2022/04/13 21:01:31 error handling event by signature Standard Input/Output Over Socket: couldn't convert arg to addr
```

The trigger was me ssh-ing into the VM.

2022-05-31 11:48 UTC, rafaeldtinoco commented
I'm moving this to draft and stale status until this is re-worked/re-discussed.

2022-12-18 13:13 UTC, yanivagman commented
@AsafEitani I see that @NDStrahilevitz is making changes in SockAddr parsing logic. Do you still want to keep this PR opened or can we close it?

2022-12-18 13:37 UTC, AsafEitani commented
Old PR

2022-12-18 13:37 UTC, closed without merging