tracee-ebpf: add security_path_symlink event
aquasecurity/tracee pull request #1490
Opened 2022-02-20 17:39 UTC by OriGlassman

2022-02-20 17:39 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/aquasecurity/tracee?pullRequest=1490) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/aquasecurity/tracee?pullRequest=1490) before we can accept your contribution.<br/><hr/>**Ori Glassman** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aquasecurity/tracee?pullRequest=1490) it.</sub>

2022-02-22 14:34 UTC, AlonZivony approved these changes
Seems good to me.
@yanivagman I think you can approve this quickly for @OriGlassman

2022-02-22 14:51 UTC, yanivagman requested changes

2022-02-22 14:51 UTC, yanivagman commented on tracee-ebpf/tracee/tracee.bpf.c
> +SEC("kprobe/security_path_symlink")
security_path_* is guarded with CONFIG_SECURITY_PATH:
https://elixir.bootlin.com/linux/latest/source/include/linux/security.h#L1767
This config is not enabled on some distros, so we better not use it, and definitely not as a default event, which will fail tracee to start.

security_inode_symlink can be used instead

2022-02-22 15:18 UTC, yanivagman commented on pkg/ebpf/c/tracee.bpf.c
> +#define SECURITY_INODE_SYMLINK           1031
please fix number indentation

2022-02-22 15:18 UTC, yanivagman commented on pkg/ebpf/events_definitions.go
> +		Sets: []string{"default", "lsm_hooks", "fs", "fs_file_ops"},
If you don't mind, let's remove this from the default set for now

2022-02-22 22:14 UTC, yanivagman commented on tracee-ebpf/tracee/tracee.bpf.c
> +SEC("kprobe/security_path_symlink")
> Fixed - There is one downside now though: 2 events are generated when a 'ln -s' is happening inside a container. One with the paths relevant for the container, and the other for the overlay fs. Unlike for when hooking security_path_symlink, which happens only in the container scope.

There might be an easy fix for this.
By looking at inode->i_sb->s_magic and comparing it to overlayfs magic number, you can know if the path is within the container or not

2022-02-23 14:42 UTC, yanivagman approved these changes

2022-02-24 10:10 UTC, merged