docs: update documentation for 0.7
aquasecurity/tracee pull request #1584
Opened 2022-03-24 14:28 UTC by rafaeldtinoco

2022-03-24 17:01 UTC, danielpacak requested changes
The updates are looking great. Still reviewing the whole PR, but I'm sharing my feedback regarding the v prefix in image tags that we added in v0.7.0-rc-1. This has impact on places where we use `{{ git.tag[1:] }}` macros. IMO we'd rather publish 0.7.0 instead of v0.7.0 to make documentation updates easier.

2022-03-24 18:03 UTC, grantseltzer commented on docs/index.md
> +loaded by default AND you will get a warning.
So dramatic @rafaeldtinoco with the capital AND

2022-03-24 21:02 UTC, rafaeldtinoco commented
@grantseltzer and @danielpacak since I'm traveling tomorrow morning (not sure about inet access) and we're releasing tomorrow, mind taking over this PR (even if you close this one and merge another one) so you both can finish the review/adjustments ?

2022-03-25 07:43 UTC, danielpacak commented on docs/index.md
> +        aquasec/tracee:{{ git.tag[1:] }}
Resolving this discussion as we've merged #1586

2022-03-25 08:24 UTC, danielpacak commented on docs/index.md
> +<a href="https://youtu.be/x2_iF0KjPKs?t=2971"><img src="https://i2.paste.pics/b755d5ee03048e3782f42da9870630eb.png?trs=a87585fdab9f70820cff773222a23ad3bbbc31d0b579bdc1b0ad91aa0cc19ecf" width="400"></
I've added this image to docs/images/tracee_video_thumbnail.png

2022-03-25 08:25 UTC, danielpacak commented on docs/index.md
> +   $ docker run \
I've done this actually.

2022-03-25 08:25 UTC, danielpacak commented on docs/index.md
> +
Fixed Markdown so it's rendered as numbered list.

2022-03-25 08:26 UTC, danielpacak commented on docs/index.md
>  - [Tracee-eBPF](https://github.com/aquasecurity/tracee/tree/{{ git.tag }}/tracee-ebpf) - Linux Tracing and Forensics using eBPF
I've updated these two links as well.

2022-03-25 08:27 UTC, danielpacak commented on docs/index.md
> +$ docker run \
Done for the docs/index.md page.

2022-03-25 08:30 UTC, danielpacak commented
> @grantseltzer and @danielpacak since I'm traveling tomorrow morning (not sure about inet access) and we're releasing tomorrow, mind taking over this PR (even if you close this one and merge another one) so you both can finish the review/adjustments ?

Let me take this over @rafaeldtinoco and push some updates to your branch. And I'll let @grantseltzer review and merge it if everything looks good.

2022-03-25 09:15 UTC, danielpacak approved these changes

2022-03-25 15:43 UTC, merged