add grafana dashboard for tracee metrics
aquasecurity/tracee pull request #1605
Opened 2022-03-28 16:13 UTC by NDStrahilevitz

Adds a json for importing a tracee metrics dashboard (for both tracee-ebpf and tracee-rules).

An example of the dashboard:
![image](https://user-images.githubusercontent.com/22661609/160441500-c90a3bd2-e899-4469-b210-c279af24d777.png)

This provides a simple demonstration of the usage for the prometheus metrics feature.

2022-03-28 16:13 UTC, NDStrahilevitz commented
I'm not sure where to actually place the dashboard file so I just guessed the appropriate location, if anyone has a better idea feel free to share it.

2022-03-28 16:32 UTC, rafaeldtinoco commented
@NDStrahilevitz what do you think about providing a small markdown under `docs/tutorials` on how to use/enable it ? Check what @danielpacak has done for vagrant:

https://github.com/danielpacak/tracee/blob/docs/tutorial/vagrant/docs/tutorials/setup-development-machine-with-vagrant.md

2022-03-28 16:42 UTC, NDStrahilevitz commented
> @NDStrahilevitz what do you think about providing a small markdown under `docs/tutorials` on how to use/enable it ? Check what @danielpacak has done for vagrant:
> 
> https://github.com/danielpacak/tracee/blob/docs/tutorial/vagrant/docs/tutorials/setup-development-machine-with-vagrant.md

Sounds like a good idea, I'll get around to it tomorrow.

2022-03-28 17:50 UTC, rafaeldtinoco requested changes
Change looks like. I think deploy/ directory is fine IMO. Requesting some documentation together with the change.

2022-03-29 09:17 UTC, NDStrahilevitz commented
@rafaeldtinoco I've added docs as requested, WDYT?

2022-03-29 10:44 UTC, rafaeldtinoco commented
I liked it. I'll merge this but, before, will change git log (it contains markdown). Thanks @NDStrahilevitz

2022-03-29 10:44 UTC, rafaeldtinoco approved these changes
Looks good, needs git log change.

2022-03-29 10:44 UTC, merged