introduce dns events
aquasecurity/tracee pull request #1618
Opened 2022-03-30 13:20 UTC by itamarmaouda101

Hi 
This PR solves #1384.

Its adds 2 new events that are part of the net events.
Also, it adds the set of the net events to the `events_definitions `map and changes the function that handles the net events to be able to handle more than one event (until today we had only one net event which is `NetPacket`).

How it works:
In the `tc_probe` function at the bpf code, I check if the packet is has a src/dst port of DNS (53) and if it's UDP.
Then it sends it with event_id of `DnsRequest` or `DnsResponse`.
in the `net_event.go` I added a function that will handle the processing of all the network events.
It basically has a switch-case with the event_id of the packet and the net events types, in case it found the event, it calls its `event_handler_function`.

Here's an example for output for trying loacte the ip of www.ubuntu.com:
`itamar@ubuntu:~/golang_env$ sudo ./dist/tracee-ebpf -t  event=dns_request,dns_response -t net=ens33 -o json
`
libbpf: Kernel error message: Exclusivity flag on, cannot modify

"timestamp":1649334493999995757,"processorId":0,"processId":759,"threadId":759,"parentProcessId":759,"hostProcessId":759,"hostThreadId":759,"hostParentProcessId":1,"userId":101,"mountNamespace":4026532596,"pidNamespace":4026531836,"processName":"systemd-resolve\u0000","hostName":"","containerId":"","eventId":"4001","eventName":"dns_request","argsNum":2,"returnValue":0,"stackAddresses":null,"args":[{"name":"metadata","type":"trace.PktMeta","value":{"src_ip":"192.168.16.134","dst_ip":"192.168.16.2","src_port":35807,"dst_port":53,"protocol":17}},{"name":"dns_questions","type":"[]bufferdecoder.DnsQueryData","value":[{"query":"www.ubuntu.com","queryType":"A","queryClass":"IN"}]}]}

{"timestamp":1649334494085087526,"processorId":0,"processId":759,"threadId":759,"parentProcessId":759,"hostProcessId":759,"hostThreadId":759,"hostParentProcessId":1,"userId":101,"mountNamespace":4026532596,"pidNamespace":4026531836,"processName":"systemd-resolve\u0000","hostName":"","containerId":"","eventId":"4002","eventName":"dns_response","argsNum":2,"returnValue":0,"stackAddresses":null,"args":[{"name":"metadata","type":"trace.PktMeta","value":{"src_ip":"192.168.16.2","dst_ip":"192.168.16.134","src_port":53,"dst_port":35807,"protocol":17}},{"name":"dns_response","type":"[]bufferdecoder.DnsResponseData","value":[{"query_data":{"query":"www.ubuntu.com","queryType":"A","queryClass":"IN"},"dns_answer":[{"answer_type":"A","ttl":5,"answer":"185.125.190.20"},{"answer_type":"A","ttl":5,"answer":"185.125.190.21"},{"answer_type":"A","ttl":5,"answer":"185.125.190.29"}]}]}]}

{"timestamp":1649334494088166734,"processorId":0,"processId":759,"threadId":759,"parentProcessId":759,"hostProcessId":759,"hostThreadId":759,"hostParentProcessId":1,"userId":101,"mountNamespace":4026532596,"pidNamespace":4026531836,"processName":"systemd-resolve\u0000","hostName":"","containerId":"","eventId":"4001","eventName":"dns_request","argsNum":2,"returnValue":0,"stackAddresses":null,"args":[{"name":"metadata","type":"trace.PktMeta","value":{"src_ip":"192.168.16.134","dst_ip":"192.168.16.2","src_port":51095,"dst_port":53,"protocol":17}},{"name":"dns_questions","type":"[]bufferdecoder.DnsQueryData","value":[{"query":"www.ubuntu.com","queryType":"AAAA","queryClass":"IN"}]}]}

{"timestamp":1649334494169898401,"processorId":0,"processId":759,"threadId":759,"parentProcessId":759,"hostProcessId":759,"hostThreadId":759,"hostParentProcessId":1,"userId":101,"mountNamespace":4026532596,"pidNamespace":4026531836,"processName":"systemd-resolve\u0000","hostName":"","containerId":"","eventId":"4002","eventName":"dns_response","argsNum":2,"returnValue":0,"stackAddresses":null,"args":[{"name":"metadata","type":"trace.PktMeta","value":{"src_ip":"192.168.16.2","dst_ip":"192.168.16.134","src_port":53,"dst_port":51095,"protocol":17}},{"name":"dns_response","type":"[]bufferdecoder.DnsResponseData","value":[{"query_data":{"query":"www.ubuntu.com","queryType":"AAAA","queryClass":"IN"},"dns_answer":[{"answer_type":"AAAA","ttl":5,"answer":"2620:2d:4000:1::26"},{"answer_type":"AAAA","ttl":5,"answer":"2620:2d:4000:1::28"},{"answer_type":"AAAA","ttl":5,"answer":"2620:2d:4000:1::27"}]}]}]}

2022-04-18 11:15 UTC, AlonZivony requested changes
Good work.
Small changes for the code to match project standards.

2022-04-18 11:15 UTC, AlonZivony commented on pkg/ebpf/c/tracee.bpf.c
> +bool should_send_payload(net_packet_t *pkt){
I think that the word we use to describe sending data from kernel to user is "submit" so I think you should call this like this.

2022-04-18 11:15 UTC, AlonZivony commented on pkg/ebpf/tracee.go
> +func (t *Tracee) netEventChoosen() bool {
Change it to `shouldTraceNetEvents`

2022-04-18 11:15 UTC, AlonZivony commented on pkg/bufferdecoder/net_decoder.go
> +	dnsLayer := packet.Layer(layers.LayerTypeDNS).(*layers.DNS)
I think that a cleaner way to do this is to use the following format:
```suggestion
	dnsLayer, ok := packet.Layer(layers.LayerTypeDNS).(*layers.DNS)
	if !ok {
```

2022-04-18 11:15 UTC, AlonZivony commented on pkg/bufferdecoder/net_decoder.go
> +	_ = copy(packetBytes[:], decoder.buffer[packetstartOffset:packetstartOffset+packetLength])
```suggestion
	_ = copy(packetBytes[:], decoder.buffer[ packetstartOffset: (packetstartOffset + packetLength)])
```

2022-04-19 07:29 UTC, itamarmaouda101 commented on pkg/ebpf/net_events.go
> +					PacketStartOff += 40 // the offset to the packet payload the size of the NetEventMetadata + NetPacketEvent
yep , put the on of the comment in incorrect place, just fixed that (:

2022-04-19 10:32 UTC, AlonZivony requested changes
Some doc changes required

2022-04-19 10:32 UTC, AlonZivony commented on pkg/ebpf/net_events.go
> +				PacketStartOff := netEventMetadata.GetSizeBytes() + netCaptureData.GetSizeBytes() // packet payload offset is NetEventMetadata + NetCaptureData
The comment here is the same as the code. It has no added value.
Please write in the comment why that packet start after both of this structs (maybe put it above the line).

2022-04-19 10:32 UTC, AlonZivony commented on pkg/ebpf/net_events.go
> +					PacketStartOff += netPacketSize // if the interface's packet should be trace we need to add another the size of NetPacketEvent
```suggestion
					 // If the interface's packet should be traced than NetPacketEvent fields are added to submitted buffer.
					 // Start offset should be updated accordingly 
					PacketStartOff += netPacketSize
```

2022-04-28 14:06 UTC, rafaeldtinoco commented
Closing this on behalf of https://github.com/aquasecurity/tracee/pull/1698 being taken care by @roikol now.

2022-04-28 14:06 UTC, closed without merging