add shared_object_loaded event
aquasecurity/tracee pull request #1631
Opened 2022-04-04 13:42 UTC by AsafEitani

This event indicates a shared object was loaded to a process.

It relies on `security_mmap_file` kprobe.
The event is only generated if the calling syscall to `security_mmap_file` is `mmap` and if the requested protection has `EXEC`.

2022-04-04 15:45 UTC, rafaeldtinoco commented
@AsafEitani mind rebasing it ? thanks!

2022-04-04 16:38 UTC, AsafEitani commented
Rebased @rafaeldtinoco

2022-04-06 08:12 UTC, AsafEitani commented
We talked about adding a few more events regarding this like mmap_file, mprotect_file, etc.
Will update this draft and convert to PR when ready

2022-04-24 09:20 UTC, AlonZivony requested changes
LGTM from the code point of view.
However, this PR is about the `shared_object_loaded` event, not `securitu_file_mprotect`.
I think you should divide this PR into 2, and open an issue for the mprotect event.

2022-05-02 07:53 UTC, yanivagman requested changes

2022-05-03 18:37 UTC, rafaeldtinoco commented on pkg/ebpf/events_definitions.go
> +			},
#1719 got merged FYI here.

2022-05-08 16:23 UTC, yanivagman approved these changes
LGTM

2022-05-08 16:24 UTC, merged