add syscall detection signature
aquasecurity/tracee pull request #1679
Opened 2022-04-18 12:25 UTC by itamarmaouda101

## Description

Hi this PR adds to tracee-rules a signeture for detecting hooking of system calls in the system call table.

I added it as an extra to the `detect_hooked_syscalls` event in tracee-ebpf
The changes i added is the signature and also a little mistake (n the derived event of `detect_hooked_syscalls`, the mistake is that the name of the event we print wasn't like in the events definition map (in the map it was `detect_hooked_syscalls` and in the drived-event it was `hooked_syscalls`)

Fixes: #1672 

Please pick one and delete the others:

- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

I add to the signature test file and test manually the `detect_hooked_syscalls` event

## Final Checklist:

- [x] My code follows the style guidelines (C and Go) of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented all functions/methods created explaining what they do.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] New and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published already.

## Git Log Checklist:

My commits logs have:

- [ ] Separate subject from body with a blank line.
- [x] Limit the subject line to 50 characters.
- [ ] Capitalize the subject line.
- [ ] Do not end the subject line with a period.
- [ ] Use the imperative mood in the subject line.
- [ ] Wrap the body at 72 characters.
- [ ] Use the body to explain what and why instead of how.

2022-04-18 16:13 UTC, AlonZivony requested changes
Looks good.
Change what I wrote and I don't see a reason for it not to be merged quickly.

2022-04-18 16:13 UTC, AlonZivony commented on pkg/ebpf/events_definitions.go
> +			{Type: "bufferdecoder.HookedSyscallData[]", Name: "hooked_syscalls"},
I can't agree with what you have done here.
If you want to export a type through signature, it should be under the `types` package.

2022-04-18 16:13 UTC, AlonZivony commented on signatures/rego/syscall_table_hooking.rego
> +    "name": "Hooking System calls by override The System call table entires",
Capitalize only the first letter.

2022-04-18 16:13 UTC, AlonZivony commented on signatures/rego/syscall_table_hooking_test.rego
> +test_match_2 {
What is the difference between test_match_1 and test_match_2?
You need to have unique tests, there is no real use to doing the same test twice.
You can test for example the behavior with 1 hooked syscall and multiple hooked syscalls as different senerios.

2022-04-28 14:52 UTC, rafaeldtinoco commented
@AsafEitani 

I believe this one will be replaced by: PR: #1705 ? If that is so, could you close this one please ?

2022-04-28 15:14 UTC, closed without merging