pkg/ebpf: use enums for enumerating defines
aquasecurity/tracee pull request #1680
Opened 2022-04-18 13:31 UTC by AlonZivony

## Description

Change constants in the C code which are enumerating values to enums.

Fixes: #1678 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

**Manual Test Setup**:

In Manjaro with kernel 5.10.101 compiled and run multiple events to check sanity.

## Final Checklist:

- [ ] My code follows the style guidelines (C and Go) of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented all functions/methods created explaining what they do.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published already.

## Git Log Checklist:

My commits logs have:

- [ ] Separate subject from body with a blank line.
- [ ] Limit the subject line to 50 characters.
- [ ] Capitalize the subject line.
- [ ] Do not end the subject line with a period.
- [ ] Use the imperative mood in the subject line.
- [ ] Wrap the body at 72 characters.
- [ ] Use the body to explain what and why instead of how.

2022-04-20 12:44 UTC, rafaeldtinoco requested changes

2022-04-20 12:44 UTC, rafaeldtinoco commented on pkg/ebpf/c/tracee.bpf.c
> +    ALERT_MMAP_W_X,
I think you missed = 1 here.

2022-04-20 12:44 UTC, rafaeldtinoco commented on pkg/ebpf/c/tracee.bpf.c
> +enum kconig_key_e {
Misspelled "kconfig" here.

2022-04-24 09:07 UTC, yanivagman reviewed
Nice!

2022-04-24 09:07 UTC, yanivagman commented on pkg/ebpf/c/tracee.bpf.c
> +    SEND_META_SIZE = 24
This shouldn't be part of the enum, but a constant

2022-04-30 22:05 UTC, AlonZivony commented
Sorry for the delay

2022-05-01 08:17 UTC, yanivagman approved these changes
LGTM!
Thanks @AlonZivony

2022-05-01 08:17 UTC, merged