cmd/tracee-ebpf: add capabilities dropping bypasses
aquasecurity/tracee pull request #2008
Opened 2022-07-24 13:26 UTC by AlonZivony

## Initial Checklist

- [ ] There is an issue describing the need for this PR.
- [ ] Git log contains summary of the change.
- [ ] Git log contains motivation and context of the change.
- [ ] If part of an EPIC, PR git log contains EPIC number.
- [ ] If part of an EPIC, PR was added to EPIC description.

## Description (git log)

Add options to bypass capabilities dropping partly or entirely
in tracee-ebpf.
This will help to solve locally capabilities issues for developers or
users which face capabilities bug.

Fixes: #1996

## Type of change

- [ ] Bug fix (non-breaking change fixing an issue, preferable).
- [ ] Quick fix (minor non-breaking change requiring no issue, use with care)
- [ ] Code refactor (code improvement and/or code removal)
- [ ] New feature (non-breaking change adding functionality).
- [ ] Breaking change (cause existing functionality not to work as expected).

## Final Checklist:

Pick "Bug Fix" or "Feature", delete the other and mark appropriate checks.

- [ ] I have made corresponding changes to the documentation.
- [ ] My code follows the style guidelines (C and Go) of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented all functions/methods created explaining what they do.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix, or feature, is effective.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published before.

## Git Log Checklist:

My commits logs have:

- [ ] Subject starts with "subsystem|file: description".
- [ ] Do not end the subject line with a period.
- [ ] Limit the subject line to 50 characters.
- [ ] Separate subject from body with a blank line.
- [ ] Use the imperative mood in the subject line.
- [ ] Wrap the body at 72 characters.
- [ ] Use the body to explain what and why instead of how.

2022-07-25 11:12 UTC, NDStrahilevitz requested changes
So I did some testing, and some UX improvements/possibly bugs that I think should be addressed:
1. `--caps add <cap_name>` doesn't work, neither does `--caps add=<cap_name>`
2. With correct usage (`--caps <cap_name>`) - giving a non real cap name (tried with `CAP_FAKE`) doesn't return any error, instead continuing execution, I think that's bad UX for a user for example if a typo is made.

2022-07-25 11:12 UTC, NDStrahilevitz commented on cmd/tracee-ebpf/internal/flags/capabilities.go
> +package flags
FYI: This file needs to move from internal

2022-07-25 11:12 UTC, NDStrahilevitz commented on docs/deep-dive/dropping-capabilities.md
> +This might cause wide variety of errors.
```suggestion
This may cause a wide variety of errors.
```

2022-07-25 11:12 UTC, NDStrahilevitz commented on docs/deep-dive/dropping-capabilities.md
> +The Tracee team try to solve bugs as quickly as possible, but it might
```suggestion
Our team tries to solve bugs as quickly as possible, but it might
```

2022-07-25 11:12 UTC, NDStrahilevitz commented on docs/deep-dive/dropping-capabilities.md
> +To solve missing capabilities errors locally, users can add capabilities
```suggestion
To fix specific missing capabilities errors locally, users can add capabilities
```

2022-07-25 11:12 UTC, NDStrahilevitz commented on docs/deep-dive/dropping-capabilities.md
> +In addition, the `--caps cancel-drop` flag could be used to cancel capabilities
```suggestion
In addition, the `--caps cancel-drop` flag can be used to cancel capability
dropping in tracee-ebpf. For docker users, the environment variable
```

2022-07-28 11:50 UTC, NDStrahilevitz commented
> So I did some testing, found two UX improvements/possibly bugs that I think should be addressed:
> 
> 1. `--caps add <cap_name>` doesn't work, neither does `--caps add=<cap_name>`
> 2. With correct usage (`--caps <cap_name>`) - giving a non real cap name (tried with `CAP_FAKE`) doesn't return any error, instead continuing execution, I think that's bad UX for a user for example if a typo is made.

Was this also addressed? If so I can check and approve.

2022-07-28 11:59 UTC, NDStrahilevitz requested changes
Ok, so there's a ux "bug" with the capability names, other than that all good so I can approve right after.

2022-07-28 11:59 UTC, NDStrahilevitz commented on cmd/tracee-ebpf/flags/capabilities.go
> +			c, err := cap.FromName(cName)
Ok, just checked this and it works but only for lower case capability names. 
So `cap_sys_admin` works but `CAP_SYS_ADMIN` doesn't, I assume library uses only lower case names for some reason. 
But in the [man page](https://man7.org/linux/man-pages/man7/capabilities.7.html) capabilities are upper case so they should probably also be supported.

2022-07-28 12:35 UTC, NDStrahilevitz requested changes
One final catch, sorry for not noticing before.

2022-07-28 12:35 UTC, NDStrahilevitz commented on cmd/tracee-ebpf/flags/capabilities.go
> +		operatorIndex := strings.IndexAny(opt, "=!<>")
Do we care here about any operators besides`=` and `!`? Also, docs don't allow for `!=` so either that logic (and operator) should be removed or it should be documented.

2022-07-28 12:55 UTC, NDStrahilevitz commented on cmd/tracee-ebpf/capabilities.go
> +	"os"
nit: this moved downwards but it should be before the github imports

2022-07-28 13:54 UTC, NDStrahilevitz commented
Please rebase this so all matrix tests can run.

2022-07-31 11:11 UTC, NDStrahilevitz reviewed
Final comment on the flag's usage examples, otherwise lgtm

2022-07-31 11:11 UTC, NDStrahilevitz commented on cmd/tracee-ebpf/flags/capabilities.go
> +		"./tracee-ebpf --%[1]s %[2]s":                         "Try capabilities drop, but continue run if failed",
In most our examples we just have `--flagname input input....` no need to have ./tracee-ebpf here

2022-08-01 10:20 UTC, NDStrahilevitz requested changes
Commit title and body got switched somehow

2022-08-02 03:11 UTC, rafaeldtinoco commented
@AlonZivony I believe https://github.com/aquasecurity/tracee/pull/2033 should be merged first and then you rebase (as that one is simpler) and then once this one is good we merge this one.

2022-08-02 08:31 UTC, AlonZivony commented
> @AlonZivony I believe #2033 should be merged first and then you rebase (as that one is simpler) and then once this one is good we merge this one.

Np, but we want it to enter to the coming sub-release so it depends if this PR will enter soon or not too.

2022-08-02 13:58 UTC, NDStrahilevitz approved these changes
LGTM!

2022-08-03 03:25 UTC, rafaeldtinoco commented
NOTE: We're waiting 0.8.1 release first before merging this one.

2022-08-14 13:01 UTC, NDStrahilevitz commented
We're into 0.8.2 cycle so this can be merged. @yanivagman or @rafaeldtinoco do you want to go over first?

2022-08-19 07:54 UTC, yanivagman approved these changes
LGTM

2022-08-19 07:54 UTC, merged