updated to golang 1.15
aquasecurity/tracee pull request #248
Opened 2020-10-10 22:51 UTC by ducksecops

Updated docker file to use build for golang 1.15 as 1.13 is now EOL as of 11thAug 2020

2020-10-13 13:39 UTC, itaysk commented
I've done some basic tests and it LGTM. @yanivagman do you have anything to add?

2020-10-13 14:06 UTC, yanivagman commented
LGTM

2020-10-13 14:17 UTC, itaysk approved these changes

2020-10-13 14:18 UTC, itaysk requested changes
can you update the gob test as well please?

2020-10-29 08:11 UTC, itaysk approved these changes

2020-10-29 08:12 UTC, merged