printer: add colorizaion of rules events
aquasecurity/tracee pull request #2511
Opened 2022-12-19 18:37 UTC by AsafEitani

## Initial Checklist

- [ ] There is an issue describing the need for this PR.
- [x] Git log contains summary of the change.
- [x] Git log contains motivation and context of the change.
- [ ] If part of an EPIC, PR git log contains EPIC number.
- [ ] If part of an EPIC, PR was added to EPIC description.

## Description (git log)
Adds colorization to the table printer on rules events.

commit bec6f3670a4f34c9e41b2b686a548332721cf43e (HEAD -> color_table, origin/color_table)
Author: AsafEitani <eitaniasaf@gmail.com>
Date:   Mon Dec 19 20:35:31 2022 +0200

    printer: add colorizaion of rules events

## Type of change

- [ ] Bug fix (non-breaking change fixing an issue, preferable).
- [ ] Quick fix (minor non-breaking change requiring no issue, use with care)
- [ ] Code refactor (code improvement and/or code removal)
- [x] New feature (non-breaking change adding functionality).
- [ ] Breaking change (cause existing functionality not to work as expected).

2022-12-19 19:11 UTC, yanivagman commented on pkg/cmd/printer/printer.go
> +	}
Instead, you can simply check if ID is between StartRulesID to MaxRulesID

2023-01-02 13:35 UTC, rafaeldtinoco commented
A change like this should be optional (set by a cmdline argument). There might be other tools parsing tracee output... having ANSI escape codes will disturb those. GNU tools usually have something like "--color=auto" or "--color=always" (or =no).

2023-01-03 13:25 UTC, AsafEitani commented
> A change like this should be optional (set by a cmdline argument). There might be other tools parsing tracee output... having ANSI escape codes will disturb those. GNU tools usually have something like "--color=auto" or "--color=always" (or =no).

Do you think that users parse the table printer? not using JSON?

2023-01-03 13:39 UTC, rafaeldtinoco commented
> Do you think that users parse the table printer? not using JSON?

TBH, I don't. But it is also a bad practice to colorize without explicitly requesting, or checking the TERMCAP support (imagine the user is running this in a vt100 terminal, or in any other terminal type that does not support colors).

2023-01-05 14:29 UTC, josedonizetti commented
@AsafEitani I like the idea of colors, and think it should be enabled by default. But also agree with @rafaeldtinoco and the user should be able to disable it. Can we go with the same solution `trivy` uses? The library `https://github.com/fatih/color` allows us to use color, and the user can set a env var to disable it, eg: `NO_COLOR=true` and unset it, if he wants color back. 

WDYT?

If you want to see an example on trivy -> https://github.com/aquasecurity/trivy/blob/main/pkg/report/table/table.go#L22

2023-01-05 17:37 UTC, rafaeldtinoco requested changes
Per last comments.

2023-01-06 10:10 UTC, AsafEitani commented
Waiting for #2541 to implement the color by severity

2023-03-14 22:25 UTC, rafaeldtinoco commented
@AsafEitani, https://github.com/aquasecurity/tracee/issues/2355 (took care of #2541) is finished. Do you really think we should colorize the output ? @josedonizetti opinions ? Maybe to have another printer (now that we support multiple printers) for the colorized output and derived from the regular table printer ? Just thinking out loud.

Converting this to draft for now.

2023-03-15 07:50 UTC, AsafEitani commented
I don't have a strong opinion, what ever you choose.

2023-03-15 22:49 UTC, rafaeldtinoco commented
Lets close this for now then. We can re-discuss if we ever think there is a need for it.

2023-03-15 22:49 UTC, closed without merging