ebpf: use new kernel symbols from libbpfgo
aquasecurity/tracee pull request #2543
Opened 2023-01-03 17:48 UTC by roikol

use new libbpgo kernel symbols Refresh method so that kernel symbols will be up-to-date throughout all components

## Initial Checklist

- [ ] There is an issue describing the need for this PR.
- [ ] Git log contains summary of the change.
- [ ] Git log contains motivation and context of the change.
- [ ] If part of an EPIC, PR git log contains EPIC number.
- [ ] If part of an EPIC, PR was added to EPIC description.

## Description (git log)

```
Author: RoiKol <roi.kol@aquasec.com>
Date:   Tue Jan 3 19:47:02 2023 +0200

    ebpf: use new kernel symbols from libbpfgo
    
    use new libbpgo kernel symbols Refresh method so that
    kernel symbols will be up-to-date throughout all components
```

Fixes: #2526

## Type of change

- [ ] Bug fix (non-breaking change fixing an issue, preferable).
- [ ] Quick fix (minor non-breaking change requiring no issue, use with care)
- [ ] Code refactor (code improvement and/or code removal)
- [ ] New feature (non-breaking change adding functionality).
- [ ] Breaking change (cause existing functionality not to work as expected).

## How Has This Been Tested?

Tests being included in this PR:

- [ ] Test File A
- [ ] Test File B

Reproduce the test by running:

- command 01
- command 02

## Final Checklist:

Pick "Bug Fix" or "Feature", delete the other and mark appropriate checks.

- [ ] I have made corresponding changes to the documentation.
- [ ] My code follows the style guidelines (C and Go) of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented all functions/methods created explaining what they do.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix, or feature, is effective.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published before.

## Git Log Checklist:

My commits logs have:

- [ ] Subject starts with "subsystem|file: description".
- [ ] Do not end the subject line with a period.
- [ ] Limit the subject line to 50 characters.
- [ ] Separate subject from body with a blank line.
- [ ] Use the imperative mood in the subject line.
- [ ] Wrap the body at 72 characters.
- [ ] Use the body to explain what and why instead of how.

2023-01-03 17:55 UTC, rafaeldtinoco requested changes
the bump (go.mod and go.sum) should have their own commit (sorry, it has been our standard).

2023-01-04 14:53 UTC, NDStrahilevitz commented on pkg/ebpf/tracee.go
> +		err = t.NewKernelSymbols()
I'd like to move to the Lazy symbols in this PR. I've ran our internal e2e on it before so it should be good to go.

2023-01-05 17:34 UTC, rafaeldtinoco reviewed
LGTM. I'll let Nadav merge once you change it to the LazyKernelSymbol like he requested (as he has already tested it).

2023-01-08 10:01 UTC, roikol commented
> LGTM. I'll let Nadav merge once you change it to the LazyKernelSymbol like he requested (as he has already tested it).

currently waiting for this PR to be merged in libbpfgo - https://github.com/aquasecurity/libbpfgo/pull/283

2023-01-11 13:14 UTC, NDStrahilevitz approved these changes

2023-01-11 17:48 UTC, rafaeldtinoco approved these changes

2023-01-11 17:49 UTC, merged