types: omit container fields if empty
aquasecurity/tracee pull request #2606
Opened 2023-01-19 10:34 UTC by josedonizetti

Working on the tracee-action, we want to show the user's signatures triggered by the pipeline in a PR comment in JSON. But the JSON gets really noisy with a lot of empty fields related to containers for events that are not container related, so I thought we could omit those fields if empty, not sure though if this would affect other things.

2023-01-19 10:35 UTC, josedonizetti commented
@NDStrahilevitz @yanivagman  WDYT?

2023-01-19 11:32 UTC, NDStrahilevitz requested changes
To see if this works you need to point types at the commit or do
`replace github.com/aquasecurity/tracee/types => ./types` in `go.mod`.
Do that, run with our e2e then we can decide.
I'd also rather keep `containerId` even if empty at least so filtering for container/non-container based on that alone would be enough.

2023-02-05 23:01 UTC, rafaeldtinoco commented
> Do that, run with our e2e then we can decide.

I thought the e2e tests would mangle the types by themselves (not replacing for the latest, but replacing because of compatibility with builtin.so from the internal rules.

2023-02-22 14:41 UTC, NDStrahilevitz commented
I'm doing this change now in #2760, can we close in favor?

2023-02-22 17:12 UTC, closed without merging