Typo Corrected in README.md to sound more meaningfull
aquasecurity/tracee pull request #262
Opened 2020-10-15 17:26 UTC by echobash

2020-10-18 07:10 UTC, itaysk commented
Thank you for spotting this typo. I think it's better to change it to `If you use the Tracee binary`, to work with the rest of the text. Please make the change and I'll accept it

2020-10-18 07:11 UTC, itaysk requested changes
Thank you for spotting this typo. I think it's better to change it to If you use the Tracee binary, to work with the rest of the text. Please make the change and I'll accept it

2020-10-18 14:46 UTC, echobash commented
Yeah That sounds better. Thank you.

2020-10-19 07:00 UTC, itaysk approved these changes

2020-10-19 07:01 UTC, merged