Additional tracing modes
aquasecurity/tracee pull request #268
Opened 2020-10-21 10:54 UTC by pathtofile

Replaces PR https://github.com/aquasecurity/tracee/pull/265 as  this was quicker than undoing that bad rebase.

Discussion: https://github.com/aquasecurity/tracee/issues/221

2020-10-21 10:56 UTC, pathtofile commented
@yanivagman - Apologies, this was quicker for me than fixing the bad rebase on the other branch.

All changes to https://github.com/aquasecurity/tracee/pull/265 have been done, and it's now actually squashed into a single commit

2020-10-21 12:44 UTC, yanivagman commented on tracee/consts.go
> +	ModeProcessAll uint32 = iota
One thing that I noticed is that when I'm now running tracee in container mode (using your PR code, "-t c"), I'm getting events which are not related to containers.
Took me some time to figure this out, but the reason for this is that ModeProcessAll value is 0.
For this reason, when loading the bpf programs, and while we still didn't set the maps (specifically, the config map with  the mode value), the default mode chosen is ModeProcessAll, and possibly non relevant processes can be traced as well...

Lucky for us, the solution is simple - just change the enum to start from 1 (iota + 1), and respectively shift the defines in the C code by one as well

2020-10-21 12:44 UTC, yanivagman requested changes
One last fix required :-)

2020-10-23 04:41 UTC, pathtofile commented
Done last fix, and still a single commit :-)

2020-10-23 05:27 UTC, yanivagman commented
Great!
Thanks @pathtofile !

2020-10-23 05:27 UTC, yanivagman approved these changes

2020-10-23 05:27 UTC, merged

2020-10-23 12:53 UTC, yanivagman commented
@pathtofile I just noticed that the commit you pushed has the wrong author details. This probably happened when you performed the merge of the commits, and took one commit more than needed.

As we want the credit for this commit will belong to the right owner, what we can do is that you will revert this commit, and re-commit it (do a PR with two commits, one for revert, and another one with the same code and correct author details) and I will approve and merge the changes.

2020-10-24 06:43 UTC, pathtofile commented
@yanivagman oof, really sorry, 2nd git mixup for this feature. I've pushed up a commit with an amended authorship: https://github.com/aquasecurity/tracee/pull/271