Add user output formatting
aquasecurity/tracee pull request #283
Opened 2020-10-29 15:11 UTC by siddharths2710

Resolves #207 

For a sample command `./tracee -o table=pid, ppid, processName, args`, the trace appears as below:

```
30196 30107 runc pathname: /sys/kernel/mm/hugepages, flags: O_RDONLY|O_LARGEFILE, dev: 21, inode: 3326
30196 30107 runc dirfd: -100, pathname: /sys/kernel/mm/hugepages, flags: O_RDONLY|O_CLOEXEC, mode: 0
30196 30107 runc fd: 3, dirp: 0xC0000D4000, count: 8192
30196 30107 runc fd: 3, dirp: 0xC0000D4000, count: 8192
30196 30107 runc flags: CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, stack: 0x7F4B6A7FBFB0, parent_tid: 0x7F4B6A7FC9D0, child_tid: 0x0, tls: 139961886033664
30196 30107 runc pathname: /run/containerd/io.containerd.runtime.v1.linux/moby/1c5210ca342c210d1c5d1120fb53e3a9515fec6508202feceb4f301b5d1a060e/log.json, flags: O_WRONLY|O_CREAT|O_APPEND|O_SYNC|O_LARGEFILE, dev: 23, inode: 693
30196 30107 runc dirfd: -100, pathname: /run/containerd/io.containerd.runtime.v1.linux/moby/1c5210ca342c210d1c5d1120fb53e3a9515fec6508202feceb4f301b5d1a060e/log.json, flags: O_WRONLY|O_CREAT|O_APPEND|O_SYNC|O_CLOEXEC, mode: 0
30196 30107 runc pathname: /proc/30196/uid_map, flags: O_RDONLY|O_LARGEFILE, dev: 4, inode: 5986944
30196 30107 runc dirfd: -100, pathname: /proc/self/uid_map, flags: O_RDONLY|O_CLOEXEC, mode: 0
30196 30107 runc fd: 5
30196 30107 runc pathname: /run/docker/runtime-runc/moby/1c5210ca342c210d1c5d1120fb53e3a9515fec6508202feceb4f301b5d1a060e/state.json, flags: O_RDONLY|O_LARGEFILE, dev: 23, inode: 700
```

Signed-off-by: Sid Srinivas <siddharths2710@yahoo.com>

2020-10-29 18:36 UTC, itaysk requested changes
@siddharths2710 thank you. the output should be printed in a table, and therefore you need to preserve the spacing when printing each event. additionally it would be better make the parsing of user input one, during init, instead of every time an event is printed

2020-10-30 04:50 UTC, siddharths2710 commented
@itaysk Could you have a look? Since the code must be generic, I'm handling it through tab spacing. The only place I'm seeing a problem is when the args field is added in the middle.

2020-10-30 04:52 UTC, siddharths2710 commented
@itaysk for the parsing, could I make use of a pre-compiled go template from Init? This way the template must simply be executed in the Print function.

2020-10-30 16:48 UTC, itaysk commented
I still don't see the expected outcome. the result I'm seeing doesn't look like a table (also, args was printed unnecessarily)
```
❯ sudo dist/tracee -o table=pid,hostname | head -n10
pid     hostname
31773
pathname: /usr/bin/ls, argv: [ls]
31773
pathname: /usr/bin/ls, dev: 8388610, inode: 777
31773
pathname: /etc/ld.so.preload, mode: R_OK
31773
pathname: /etc/ld.so.cache, flags: O_RDONLY|O_LARGEFILE, dev: 8388610, inode: 526365
31773
^C%            
```

2020-10-30 16:53 UTC, itaysk commented
tab separation doesn't work well for a table:
```
pid     hostName        eventId
31823   ubuntu  59
pathname: /usr/bin/ls, argv: [ls]
31823   ubuntu  339
pathname: /usr/bin/ls, dev: 8388610, inode: 777
31823   ubuntu  21
pathname: /etc/ld.so.preload, mode: R_OK
31823   ubuntu  340
pathname: /etc/ld.so.cache, flags: O_RDONLY|O_LARGEFILE, dev: 8388610, inode: 526365
31823   ubuntu  257
```

2020-10-31 11:12 UTC, siddharths2710 commented
@itaysk I've incorporated the format spacing corresponding to each event attribute now, and it seems to match. I've used go-template to achieve the same. Could you have a look?

2020-10-31 13:11 UTC, itaysk commented
@siddharths2710 `args` still show up unexpectedly.  table is still not properly aligned. 

additionally, instead of looking for different casing of vars, should do a "toLowercase" before the matching the string, so that all casing options will be matched. also need to error when unknown field is given

2020-10-31 13:11 UTC, itaysk commented
additionally, instead of looking for different casing of vars, should do a "toLowercase" before the matching the string, so that all casing options will be matched. also need to error when unknown field is given

2020-11-08 14:34 UTC, itaysk commented
Hi @siddharths2710 are you still working on this? if you wanted to complete this work, we can make an exception and include this for your hacktoberfest contributions. if you want to let this go that's also fine since it appeared to be more complicated than originally thought.

2020-11-09 16:15 UTC, siddharths2710 commented
@itaysk I'm really sorry since I just haven't had the time for pursuing this, and I guess I'd be free only during the December vacation :( I'll try to take this up if it's still available by then. It'd be helpful if you can update the issue #207 in any case with the extra details :)

2020-11-09 16:15 UTC, closed without merging