Feature/proctree query time
aquasecurity/tracee pull request #3691
Opened 2023-11-15 13:13 UTC by AlonZivony

### 1. Explain what the PR does

7fa990fb7 **feat(proctree): fill timestamp of proctree info objects**
fff0a47a2 **feat(types): add timestamp to proctree info objects**

### 2. Explain how to test it

e2e test

### 3. Other comments

2023-11-15 13:14 UTC, AlonZivony commented
@rafaeldtinoco WDYT?

2023-11-22 16:41 UTC, rafaeldtinoco commented on go.mod
> +replace github.com/aquasecurity/tracee/types => ./types
temporary, needs a PR type change (just marking here not to forget).

2023-11-22 16:59 UTC, rafaeldtinoco commented on tests/e2e-inst-signatures/e2e-proctree_data_source.go
> +	}
Code is correct. Logic is correct, etc. But, why ? The issue does not describe the "why" very well.

If you query for a process, or a thread, or a tree, at a specific point in time, you will get the nearest changelog timestamp item. Why there is a need to know the exact point in time ? (Im not saying I'm against). What would be the benefit ?

2023-11-22 17:03 UTC, rafaeldtinoco requested changes
LGTM. Needs a better reasoning and a PR changing the types before this can be merged. Im putting a -1 for now until both are satisfied. Request my review in the types change, please. I'll merge and you can rebase this and change types dependency to that commit.

2023-11-23 08:47 UTC, AlonZivony commented
@rafaeldtinoco I probably need your opinion on the following question:
Should the query time be part of the info objects, or be part of an enveloping type to the info objects?
In my opinion it is easier to manage as part of the info object, but I am not sure that the timestamp is an info of the process in a way that justify this coupling.
We can create a generic `TimeRelevantInfo` type, that has information and timestamp in it, and return it instead of the process and thread info objects.
WDYT?

2023-11-23 12:50 UTC, rafaeldtinoco commented
> We can create a generic `TimeRelevantInfo` type, that has information and timestamp in it, and return it instead of the process and thread info objects.

I think I prefer this idea better Alon, if you also think that.

2023-11-24 00:29 UTC, rafaeldtinoco requested changes
We agreed the location of Timestamp will be a struct called TimeRelevantInfo instead of duplicates under other Info structs.

2023-11-29 02:31 UTC, rafaeldtinoco approved these changes
LGTM

2023-11-29 02:31 UTC, merged