docs: add discussion template for adopters
aquasecurity/tracee pull request #3702
Opened 2023-11-22 11:26 UTC by AnaisUrlichs

2023-11-22 13:26 UTC, rafaeldtinoco approved these changes
LGTM (so you can merge whenever you want if Itay is +1). Cheers!

2023-11-23 06:40 UTC, itaysk approved these changes

2023-11-23 06:45 UTC, itaysk requested changes
the email is oss@aquasec.com

2023-11-23 16:57 UTC, itaysk approved these changes

2023-11-28 19:21 UTC, merged