feat(signatures): expose signatures helpers as Go module
aquasecurity/tracee pull request #3765
Opened 2023-12-17 11:34 UTC by AlonZivony

### 1. Explain what the PR does

To allow users the option to use the up-to-date helpers for Go signatures, the helpers were exported to be an external Go module.

f9a60e590 **feat(signatures): expose signatures helpers as Go module**

### 2. Explain how to test it

### 3. Other comments

2023-12-17 11:36 UTC, AlonZivony commented
This will require a follow-up PR to remove the `replace` in the `go.mod` file.

2023-12-18 12:09 UTC, yanivagman commented
Please see my comment https://github.com/aquasecurity/tracee/issues/3705#issuecomment-1826081041

2023-12-18 12:22 UTC, AlonZivony commented
Using signatures as an .so or built in is not so important to determine what to do here in my opinion.
If we import the Tracee module, we need to have sophisticated make file to run unit tests because of the cgo and all.
It is very inconvenient to work with Tracee as a dependency, and also inaccurate because Tracee use the signatures, and not vice-versa.
So dividing the helpers from Tracee to allow more healthy dependencies is the best approach regardless of the way the signatures will be integrated into the Tracee in the end

2023-12-18 13:05 UTC, NDStrahilevitz approved these changes
FWIW, i'm +1 for this change.

2024-01-22 12:03 UTC, yanivagman approved these changes
LGTM

2024-01-22 12:03 UTC, yanivagman commented on go.mod
> +replace github.com/aquasecurity/tracee/signatures/helpers => ./signatures/helpers
Please replace this after merged

2024-01-22 12:05 UTC, yanivagman requested changes

2024-01-22 12:05 UTC, yanivagman commented on go.mod
> +replace github.com/kubernetes/cri-api => k8s.io/cri-api v0.23.5-rc.0
Why is that?

2024-01-22 12:05 UTC, yanivagman commented on signatures/helpers/go.mod
> +go 1.19
Please update to 1.21

2024-01-22 16:02 UTC, yanivagman approved these changes
LGTM

2024-01-22 16:02 UTC, merged