Change inotify_watch event to security_path_notify
aquasecurity/tracee pull request #3913
Opened 2024-03-10 10:51 UTC by oshaked1

### 1. Explain what the PR does

Changed inotify_watch event to security_path_notify.
inotify_watch used the inotify_find_inode kernel function which is static and cannot be hooked on all kernels.
This replacement event hooks security_path_notify instead (using a kprobe), which is always available.
This function also handles notify requests from dnotify and fanotify, which are used for similar purposes.
The new event also includes the mask and object type fields,
which can be used to determine the exact characteristics of the watch.

### 2. Explain how to test it

Run tracee with `--events security_path_notify`, generate the event by registering a FS watch using any of the `dnotify`, `inotify` or `fanotify` APIs.

2024-03-10 10:51 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/aquasecurity/tracee?pullRequest=3913) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/aquasecurity/tracee?pullRequest=3913) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aquasecurity/tracee?pullRequest=3913) it.</sub>

2024-03-11 21:49 UTC, NDStrahilevitz commented
@yanivagman Are we ok with straight up replacing the event and breaking users? I think we should start adding new events and deprecating older versions if needed instead as a practice.
Alternatively, we could switch the probes in the event to the new one, and not touch the event at all, besides adding the new argument.

2024-03-13 16:05 UTC, oshaked1 commented
> > @yanivagman Are we ok with straight up replacing the event and breaking users? I think we should start adding new events and deprecating older versions if needed instead as a practice. Alternatively, we could switch the probes in the event to the new one, and not touch the event at all, besides adding the new argument.
> 
> You are probably right. We should keep the old event, and mark him as deprecated somehow. Then we can in a future major release remove at once all deprecated mark events.

I added back the old event. How should it be marked as deprecated?

2024-03-13 16:32 UTC, yanivagman commented
Since we're still in v0.x.y and the event is very specific and still new, I'm ok with removing it. In the future we should add the mechanism to mark events as deprecated

2024-03-14 11:20 UTC, AlonZivony approved these changes
LGTM
A very high quality code :)

2024-03-18 14:56 UTC, yanivagman requested changes

2024-03-18 14:56 UTC, yanivagman commented on pkg/events/parse_args.go
> +		}
Please note that if you use a threat detection event which is based on this event you should not rely on the parsed arguments values but on the raw arguments values

2024-03-18 14:56 UTC, yanivagman commented on tests/e2e-inst-signatures/scripts/fsnotify_tester.c
> +}
What's the use of that?

2024-03-19 07:20 UTC, oshaked1 commented on tests/e2e-inst-signatures/scripts/fsnotify_tester.c
> +}
Forgot to remove it, fixed.

2024-03-19 11:51 UTC, yanivagman approved these changes
LGTM

2024-03-19 11:52 UTC, merged