fea: added the pinned map for ns
aquasecurity/tracee pull request #405
Opened 2021-01-07 12:26 UTC by ogozman

This PR aims at adapting tracee to work with pinned maps with mount namespace ids. The implementation is done as a separate trace mode in order to not mess with other functions of tracee.

Usage example:
tracee --trace pinned_map --mntns_pin=/path/to/pinned/map
There is a point I would like to raise about this request beyond tracee mode extension itself. I have tested the application mainly with gadget-tracer from kinvolk because including tracee as an additional gadget is a primary purpose of my work. I have issues with legacy probes since several gadgets might work in parallel and use same same probems which lead to conflict. My problem was solved by using perf-based probes which libbpf.go already provides. 
I understand that legacy probes are used for compatibility reason. We can try to create a fall-back to older probes if error is raised or use older probes by default and fall back to perf-probes is case of an error, if it is still necessary to keep using legacy probes in newer version of tracee. Of course, any other suggestions about how to improve this request are very much welcome.  Thank you. 
@kinvolk @alban @mauriciovasquezbernal

2021-01-07 15:01 UTC, yanivagman requested changes
Thanks @ogozman, I hope we can make Tracee work with inspector gadget soon.
I'm not sure we need to create a new map other than the mnt_ns_filter, as it already does exactly what you are looking for. I'm also not sure we need to create a new mode. Isn't use the "all" mode in combination with the mnt_ns_filter (assuming it can be pinned after creation) should be enough?

2021-01-07 16:04 UTC, ogozman commented on main.go
> +				Name:  "mntns_pin",
Will do

2021-01-07 16:04 UTC, ogozman commented on main.go
> +	traceHelp += "'host:all'       | Trace all processes not in a container\n"
Yes, I have worked on the changes prior to most the recent changes

2021-01-07 16:05 UTC, ogozman commented on tracee/tracee.bpf.c
> +} mntns_set SEC(".maps"); //map that is used in pinned map mode to filter by mount namespaces ids
I was not aware of bpf_map__pin(), if it is available and works as expected i will try to use it instead of creating a new map.

2021-01-07 16:15 UTC, ogozman commented on tracee/tracee.go
> +				_, err = prog.AttachKprobe(probe.event)
I see, i will rework accordingly

2021-01-07 16:18 UTC, ogozman commented
Thank you for the review @yanivagman. Before I will try to make the changes to remove separate mode per your suggestion I wanted to clear one thing up: with the configuration suggested by you, will the keys (which represent mnt ns ids) with value equal to 0 be traced?

2021-01-07 16:28 UTC, yanivagman commented
Value 0 will not be traced (any other value will be).
If that's a problem that can't be handled on your side (setting the value to a non 0 value), you can keep the trace mode, and use it in the bpf code to not care about the value if it is set.

A comment about using bpf_map__pin(). You will probably need to use it before BPFLoadObject() is called in initBPF()

2021-01-07 17:36 UTC, yanivagman commented
@ogozman ,
To avoid future changes (again :-)), I think we should actually call the flag just "pin" (as other bpf objects can be pinned as well, and maybe we will want to add such support in the future).
The flag should look like this:
`--pin map:mnt_ns_filter:/path/to/pin`

Thanks

2021-01-20 13:21 UTC, ogozman commented
Hello, @yanivagman , I am currently trying to port pinned map to the newest version of tracee, however, with recent updates, after the loading of bpf programm. the pinned maps, if they preexisted, are not able to be found. This is not the case with older version of tracee, where pinning works without problem. Do you know what might be causeing this issue?

2021-01-20 14:28 UTC, yanivagman commented
@ogozman I'm not sure I understand what happen - the maps are deleted after BPFLoadObject()?
all the pinning stuff should happen before loading (BPFLoadObject()) the bpf programs. Are you using the bpf_map__pin() API like we discussed or changing the map pin using bpf_map__set_pin_path()?

2021-01-20 14:39 UTC, ogozman commented
I am using GetMap in order to check whether the map is present before pinning, it is present, I pin it via bpf_map__pin(), bpf_map__change_pin_path() produces the same effect. I check again if the map is present, it is. Then filter init commences after bpfloadobject() is called. Just to acitvate filter i call with mntns=0, it tries to get the map in setUintFilter() function and does not find it anymore

2021-01-20 14:50 UTC, ogozman commented
What is interesting is that it does not happen if create a different map and try to pin it. It is still there after bpfloadobject()

2021-01-20 14:51 UTC, yanivagman commented
I need to see the code.
Can you point me to it in your fork or maybe push a draft PR here?

2021-01-20 14:54 UTC, ogozman commented
Absolutely, thank you very much! https://github.com/ogozman/tracee-1

2021-01-20 16:19 UTC, yanivagman commented
So I successfully pinned a map using your code with a small modification.
bpf_map__pin() should be called AFTER BPFLoadObject() and (unlike what I mistakenly told you).
Also, you need to unpint the map (bpf_map__unpin()) after tracee exits, or otherwise - path exists error will arise.

I used the following line after I compiled the code with the above change:
`sudo ./dist/tracee --pin map:mnt_ns_filter:/sys/fs/bpf/mnt`

And got no errors

2021-01-20 16:40 UTC, ogozman commented
It does not look like the map is getting actually pinned if i call loading the object. When i provide path to existing map (which is my endgoal), neither are the mount namespaces from there tracked, nor is an entry added to it if you provide an entry via trace mntns=ns_id 
Also the map is not created in the path i provide if none existed. It seem that in this case the pinning is ignored. This is what happens in my case.

2021-01-20 16:42 UTC, yanivagman commented
That's strange, because I do see the path created, and I use a map which already exists (mnt_ns_filter)

2021-01-20 16:48 UTC, yanivagman commented
Can you please test with my branch:
https://github.com/yanivagman/tracee/tree/pin_map

And tell me if a map is created for you in /sys/fs/bpf with the following line:
`sudo ./dist/tracee --pin map:mnt_ns_filter:/sys/fs/bpf/mnt`

2021-01-20 17:10 UTC, ogozman commented
If I call tracee like this, there will be no filtering because mnt ns filter is not turned on. Unless the functioning of it changed. In my map i have ids as keys and 1 as value.

2021-01-20 17:15 UTC, yanivagman commented
So how else do you call tracee? I'm not sure what you are planning to do, but you need to give the pinning code a map which is already part of tracee bpf code, which are defined in the MAPS section in tracee.bpf.c.
This is what I thought you were trying to do, and this is why we defined mnt_ns_filter (which is defined by tracee to filter by mntns) to use the same types that you use in inspector-gadget (u64->u32)

2021-01-20 17:16 UTC, ogozman commented
Yes, but  you are understanding correctly. The trouble that when i simply pin the map, no filtering happens because, i guess, filter is turned off by default, right?

2021-01-20 17:16 UTC, yanivagman commented
Of course, you will also have to set the "enabled" flag for this map

2021-01-20 17:24 UTC, yanivagman commented
Edited my comment above with the lines to enabled the map (should be part of initBPF)

2021-01-20 17:42 UTC, ogozman commented
When I try to pin the map created by gadget-tracer on your branch I get 
libbpf: failed to pin map: File exists

2021-01-20 17:46 UTC, yanivagman commented
As I said in a previous comment, you need to use the unpin__map api or otherwise you might get such errors (because the path indeed exists)

2021-01-20 17:53 UTC, ogozman commented
Do you mean the path to actual map? This file (path) is created by gadget-tracer, as such, it always exists when i start tracee with pinned map, since i want to used the map filled by gadget-tracer to filter

2021-01-20 17:58 UTC, yanivagman commented
So now I refer you to my other comment:

> So how else do you call tracee? I'm not sure what you are planning to do, but you need to give the pinning code a map which is already part of tracee bpf code, which are defined in the MAPS section in tracee.bpf.c.

If you are using a map which already existed before (and in fact, was also pinned before) - this method will not work

2021-01-20 18:12 UTC, ogozman commented
Hm, i am not sure why there would no way to make this work, since it works with separate mode and map that already exists in the code. I am in no way expirience in this kind of programming, so, please, excuse my ignorance. similar methods worked in my previous pull request and works here with separate mode: i pushed the changes just now  https://github.com/ogozman/tracee-1

2021-01-20 18:39 UTC, yanivagman commented
That's interesting.
You say that it works when you have an existing map already pinned, and the path already exists before tracee started?

2021-01-20 18:47 UTC, ogozman commented
Yes. my assumption is that it may be the name of the map. Since i add new map, i give it exactly same name as in inspector-gadget, I will try with different name to see if it breaks

2021-01-20 19:05 UTC, yanivagman commented
An easy test for your assumption will be to rename the mnt_ns_filter map to the value that worked for you, and use the latest code that pins after load. If this is indeed the reason, we can further check why this is happening

2021-01-20 21:08 UTC, yanivagman commented
@ogozman I think we can start by pushing the libbpfgo changes as it has its own go module and we already know that the wrappers you wrote are working. We can add these three wrappers:
Bpf_map_pin(), bpf_map__unpin() and bpf_map__set_pin_path().
I can do it if you want, but as you already wrote most of these wrappers, this should be straightforward.

We can then open another PR for adding the "pin" flag which will pin maps using the bpf_map__pin() wrapper. Again, you already did most of this work and we know that it's working.

After having the above merged, we can finish the work of the integration with inspector-gadget, and I will try to help wherever I can.

Is this ok with you?

2021-01-20 21:26 UTC, ogozman commented
Yes, it is fine with me. I will prepare libbpfgo update and open PR  and then open one with pin flag

2021-01-27 11:14 UTC, closed without merging