fix(ebpf): assert as uint64 when value is not nil
aquasecurity/tracee pull request #4332
Opened 2024-09-26 20:02 UTC by geyslan

Close: #4330

### 1. Explain what the PR does

3e967aec6 **fix(ebpf): assert as uint64 when value is not nil**

```
The normalizeTimeArg function was not checking if the value was nil
before asserting it as an uint64.
```

### 2. Explain how to test it

### 3. Other comments

2024-09-27 10:24 UTC, NDStrahilevitz reviewed
In what case will a time arg be nil?

2024-09-27 12:05 UTC, geyslan commented
> In what case will a time arg be nil?

Currently, when not using proctree, see:

`sudo ./dist/tracee -e sched_process_fork`

```
17:35:12:005276  1000   IPDL Background  16017   16052   0                sched_process_fork        parent_tid: 16052, ..., **parent_process_start_time: <nil>**, leader_tid: <nil>, leader_ns_tid: <nil>, leader_pid: <nil>, leader_ns_pid: <nil>, leader_start_time: <nil>
```

`sudo ./dist/tracee --proctree source=both -e sched_process_fork`

```
17:37:29:009715  1000   firefox          16017   16017   0                sched_process_fork        parent_tid: 16017, ..., **parent_process_start_time: 1727389186434828788**, leader_tid: 16017, leader_ns_tid: 16017, leader_pid: 16017, leader_ns_pid: 16017, leader_start_time: 1727389260327760332
```

2024-09-27 12:07 UTC, NDStrahilevitz commented
> > In what case will a time arg be nil?
> 
> Currently, when not using proctree, see:
> 
> `sudo ./dist/tracee -e sched_process_fork`
> 
> ```
> 17:35:12:005276  1000   IPDL Background  16017   16052   0                sched_process_fork        parent_tid: 16052, ..., **parent_process_start_time: <nil>**, leader_tid: <nil>, leader_ns_tid: <nil>, leader_pid: <nil>, leader_ns_pid: <nil>, leader_start_time: <nil>
> ```
> 
> `sudo ./dist/tracee --proctree source=both -e sched_process_fork`
> 
> ```
> 17:37:29:009715  1000   firefox          16017   16017   0                sched_process_fork        parent_tid: 16017, ..., **parent_process_start_time: 1727389186434828788**, leader_tid: 16017, leader_ns_tid: 16017, leader_pid: 16017, leader_ns_pid: 16017, leader_start_time: 1727389260327760332
> ```

That's odd. Sounds to me like that is the bug.

2024-09-27 12:35 UTC, geyslan commented
If you're not using proctree, it should have been fed by the control plane signal, right?

2024-09-27 12:38 UTC, NDStrahilevitz commented
Ok so these arguments are sort of "metadata" arguments which are submitted on a need basis for the process tree. I then question what merit they have as arguments. Arguments or as want to call it "event data" should reflect user informative data on the event. If this is not such data, that is, it is some sort of "metadata" argument, then that reflects an issue in the event format.
Further, it implies that the processing should be applied conditionally. WDYT?
@yanivagman @itaysk I think we need to take this usecase into account in https://github.com/aquasecurity/tracee/issues/2870 (event specific "data" which is relevant for internal logic but not for the user)

2024-09-27 12:57 UTC, geyslan commented
> Further, it implies that the processing should be applied conditionally. WDYT?

It is:

https://github.com/aquasecurity/tracee/blob/1a0065b370320fd55eae7eb952719f0e785ec2a0/pkg/ebpf/processor.go#L100-L102

2024-09-27 12:59 UTC, NDStrahilevitz commented
@geyslan 

The relevant processor is here https://github.com/aquasecurity/tracee/blob/1a0065b370320fd55eae7eb952719f0e785ec2a0/pkg/ebpf/processor.go#L88

2024-09-27 13:03 UTC, geyslan commented
Nice. This makes sense to me now. So yeah, I believe it should be in the condition below.

2024-10-07 16:00 UTC, NDStrahilevitz requested changes

2024-10-07 16:00 UTC, NDStrahilevitz commented on pkg/ebpf/processor.go
> +		// Event Timestamps Normalization
Logically this works. But I would rather have it in a separate section to convey the intention of all timestamp arguments being registered and processed first. I do think that an effort in another PR of yours may help us move this logic from the processing alltogether, I'll elaborate there.

2024-10-10 07:19 UTC, NDStrahilevitz approved these changes
I want to resolve this properly with the changes to argument typing (and thus move this logic to decoding timestamp args).
So for now, lets merge this and more importantly cherry-pick to the v0.22.3 release so that users don't receive the repeated errors.

2024-10-10 13:54 UTC, geyslan commented
/fast-forward

2024-10-10 13:54 UTC, merged