Add Traceectl to Tracee
aquasecurity/tracee pull request #4396
Opened 2024-11-25 10:54 UTC by ShohamBit

### Description

This PR introduces `traceectl`, a new CLI tool for interacting with Tracee. It implements basic commands for communication with Tracee via gRPC.

### Key Changes

- Added `traceectl` CLI tool.
- Implemented commands for:
    - `version`
    - `metrics`
    - `stream`
    - `event`

### Testing

1. **Compile and run Tracee with gRPC:**

   ```bash
   make tracee
   tracee --grpc-listen-addr unix:/tmp/tracee.sock
   ```

2. **Run `traceectl`:**

   ```bash
   go run ./cmd/traceectl/main.go
   ```

   This displays the help command.

### Current Limitations

- `metrics`:  JSON output is not yet supported.
- `stream`: Only the base `stream` command is supported (no subcommands). It streams events directly from Tracee.
- `policy` and `plugin` commands are not yet supported.

### Related Issues

- Resolves #4387 (accidentally closed)

---

**Note:** This PR was accidentally closed previously and is now being resubmitted.

2024-11-27 12:57 UTC, yanivagman requested changes
Please see comments below.
In addition, please add documentation to traceectl.
As part of the documentation, please also refer to the way the user should start tracee "daemon" (e.g. using NONE output and setting the grpc server address)

2024-11-27 12:57 UTC, yanivagman commented on cmd/traceectl/cmd/event.go
> +	Get descriptions of events and run them.
```suggestion
	Get descriptions of events.
```

2024-11-27 12:57 UTC, yanivagman commented on cmd/traceectl/cmd/event.go
> +	describeEventCmd.Flags().StringVarP(&eventOutputFlag, "output", "o", "stdout", "Output destination ")
Output can be made global instead of per command

2024-11-27 12:57 UTC, yanivagman commented on cmd/traceectl/pkg/client/client.go
> +		}
switch case should only initialize address, common code can be below

2024-11-27 12:57 UTC, yanivagman commented on cmd/traceectl/pkg/client/client.go
> +	}
this is redundant

2024-11-27 12:57 UTC, yanivagman commented on cmd/traceectl/pkg/cmd/formatter/JSONFormatter.go
> +	f.CMD.Printf("%s", event.String())
nit: use camelCase

2024-11-27 12:57 UTC, yanivagman commented on cmd/traceectl/pkg/cmd/formatter/JSONFormatter.go
Since these functions are tightly coupled to the stream and events commands, I suggest to put them in their packages, and leave the formatter out at this stage

2024-11-27 12:57 UTC, yanivagman commented on cmd/traceectl/pkg/cmd/formatter/TableFormatter.go
The methods in this file are coupled to the command - let's move them to the respective commands instead. In the future, we can think about extending traceectl with a formatter package

2024-11-27 12:57 UTC, yanivagman commented on cmd/traceectl/pkg/cmd/formatter/formatter.go
> +}
This function doesn't seem to be part of the formatter package, considering it handles output

2024-11-27 12:57 UTC, yanivagman commented on cmd/traceectl/pkg/cmd/printer/printer.go
ditto

2024-11-28 08:51 UTC, ShohamBit commented on cmd/traceectl/pkg/cmd/printer/printer.go
I will remove printer in its entirety

2024-11-28 13:29 UTC, geyslan commented on cmd/traceectl/cmd/event.go
> +	`,
```suggestion
Let you enable and disable events in tracee.
Get descriptions of events.
`,
```

2024-11-28 13:33 UTC, geyslan commented on cmd/traceectl/cmd/event.go
> +	response, err := traceeClient.GetEventDefinitions(context.Background(), &pb.GetEventDefinitionsRequest{EventNames: args})
nit: do prefer inserting a empty line after defer settings leaving it in a separate block.

```suggestion
	}
	defer traceeClient.CloseConnection()

	response, err := traceeClient.GetEventDefinitions(context.Background(), &pb.GetEventDefinitionsRequest{EventNames: args})
```

2024-11-28 13:33 UTC, geyslan commented on cmd/traceectl/cmd/event.go
> +
```suggestion
```

2024-11-28 14:47 UTC, ShohamBit commented
What do you think about adding a flag to traceectl version command called `short` for a short version instead of all the info we get, or the exact offset making the `long` flag and the short version the default?

2024-11-28 14:47 UTC, ShohamBit commented on cmd/traceectl/cmd/event.go
> +		format.PrintJson(response.String())
That's a great point to note, I think that's not really matter where the conversion take place, as you already said the info parsed between trace and tracectl is in JSON.

2024-11-28 22:06 UTC, geyslan commented
> What do you think about adding a flag to traceectl version command called `short` for a short version instead of all the info we get, or the exact offset making the `long` flag and the short version the default?

I believe we wouldn't bother with it. When it's from a released version, it's already short.

2024-11-28 22:14 UTC, geyslan commented on cmd/traceectl/cmd/stream.go
> +		//Error: output format not supported
Maybe printing a not supported error.

2024-12-03 21:07 UTC, geyslan commented
Gonna through this tomorrow. 👍🏻

2024-12-04 10:32 UTC, ShohamBit commented on cmd/traceectl/pkg/mock/server.go
> +	ExpectedVersion string             = "v0.22.0-15-gd09d7fca0d"
Update this output when writing test to version command or remove it entirely

2024-12-04 10:34 UTC, ShohamBit reviewed
Looks great to me, maybe go over the documentation and review it once more

2024-12-04 11:35 UTC, geyslan commented
@ShohamBit @yanivagman what do you think about splitting this? Since we already have a working stream command, we could open a PR with just the base root and stream commands to establish a foundation for the upcoming new commands (each added in separate PRs). This approach would make both implementation and review more manageable.

2024-12-04 13:13 UTC, ShohamBit commented
Hey @geyslan, great thinking, let's discuss this over with @yanivagman

2024-12-05 11:32 UTC, yanivagman requested changes
First pass...

2024-12-05 11:32 UTC, yanivagman commented on cmd/traceectl/cmd/stream.go
> +		return fmt.Sprintf("%v", v.UInt64Array.Value)
```suggestion
		var result []string
		for _, val := range v.UInt64Array.Value {
			result = append(result, strconv.Itoa(int(val)))
		}
		return strings.Join(result, ", ")
```

2024-12-05 11:32 UTC, yanivagman commented on cmd/traceectl/pkg/client/client.go
> +		return nil, err
```suggestion
		return nil, err
```

Let the caller decide to log or not

2024-12-05 11:32 UTC, yanivagman commented on cmd/traceectl/pkg/client/diagnostic.go
> +		return
```suggestion
		log.Printf("Failed to close connection: %v", err)
```

2024-12-05 11:32 UTC, yanivagman commented on cmd/traceectl/pkg/client/service.go
> +		return
```suggestion
		log.Printf("Failed to close connection: %v", err)
```

2024-12-05 11:32 UTC, yanivagman commented on cmd/traceectl/pkg/cmd/flags/output.go
> +		if output == "" || strings.TrimSpace(output) == "" {
```suggestion
	if output != "" && output != "stdout" { 
		if strings.TrimSpace(output) == "" {
```

2024-12-05 11:32 UTC, yanivagman commented on cmd/traceectl/pkg/cmd/flags/output.go
> +		file, err := os.Create(output)
```suggestion
		file, err := os.OpenFile(output, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, 0644)
```

2024-12-05 11:32 UTC, yanivagman commented on cmd/traceectl/pkg/cmd/flags/output.go
> +		// Make sure to close the file after execution
```suggestion
		// Close the file after execution
```

2024-12-05 11:32 UTC, yanivagman commented on cmd/traceectl/pkg/cmd/formatter/jsonFormat.go
This file can be merged into formatter.go

2024-12-05 11:32 UTC, yanivagman commented on cmd/traceectl/pkg/cmd/formatter/tableFormat.go
This file can be merged into formatter.go

2024-12-05 11:32 UTC, yanivagman commented on docs/docs/traceectl/commands/event.md
> +The `event` command in **TraceeCtl** is used for managing events within Tracee. It allows you to list, describe, enable, and disable various event types that Tracee can capture. Below is the usage gu
```suggestion
The `event` command in **traceectl** is used for managing events within Tracee. It allows you to list, describe, enable, and disable various event types that Tracee can capture. Below is the usage guide for the `event` command and its subcommands.
```

2024-12-05 11:32 UTC, yanivagman commented on docs/docs/traceectl/commands/event.md
> +The `event` command in TraceeCtl is a powerful tool for managing Tracee's event capabilities. Use the `list`, `describe`, `enable`, and `disable` subcommands to gain detailed insight and control over
```suggestion
The `event` command in traceectl is a powerful tool for managing Tracee's event capabilities. Use the `list`, `describe`, `enable`, and `disable` subcommands to gain detailed insight and control over the events Tracee monitors.
```

2024-12-05 11:32 UTC, yanivagman commented on docs/docs/traceectl/commands/metrics.md
> +The `metrics` command in **TraceeCtl** provides information about Tracee's performance and resource usage metrics. This command is helpful for monitoring how Tracee is functioning in real-time.
```suggestion
The `metrics` command in **traceectl** provides information about Tracee's performance and resource usage metrics. This command is helpful for monitoring how Tracee is functioning in real-time.
```

2024-12-05 11:32 UTC, yanivagman commented on docs/docs/traceectl/commands/metrics.md
> +The `metrics` command in TraceeCtl allows users to obtain insights into Tracee's operational metrics, including event counts and resource usage. The command supports a table output format to suit dif
This summary looks redundant

2024-12-05 11:32 UTC, yanivagman commented on docs/docs/traceectl/commands/stream.md
> +The `stream` command in **TraceeCtl** allows users to stream events directly from Tracee in real time. This command provides flexible output formats for better integration and readability.
```suggestion
The `stream` command in **traceectl** allows users to stream events directly from Tracee in real time. This command provides flexible output formats for better integration and readability.
```

2024-12-05 11:32 UTC, yanivagman commented on docs/docs/traceectl/commands/stream.md
> +The `stream` command in TraceeCtl is a useful tool for monitoring Tracee events in real time, with options for JSON or table output. Use this command to keep track of activities and ensure comprehens
This summary looks redundant

2024-12-05 11:32 UTC, yanivagman commented on docs/docs/traceectl/commands/version.md
> +The `version` command in **TraceeCtl** provides detailed information about the current version of the tool. This includes the version number, build date, and other relevant metadata.
```suggestion
The `version` command in **traceectl** provides detailed information about the current version of the tool. This includes the version number, build date, and other relevant metadata.
```

2024-12-05 11:32 UTC, yanivagman commented on docs/docs/traceectl/flags/format.md
> +The `--format` flag in **TraceeCtl** is used to specify the output format for certain commands. Currently, this flag supports the following values for the `stream`, `event list`, and `event describe`
```suggestion
The `--format` flag in **traceectl** is used to specify the output format for certain commands. Currently, this flag supports the following values for the `stream`, `event list`, and `event describe` commands:
```

2024-12-05 11:32 UTC, yanivagman commented on docs/docs/traceectl/flags/server.md
> +The `--server` flag in **TraceeCtl** is used to specify the connection type that TraceeCtl should use to communicate with the Tracee server. This connection type can be either **Unix socket** or **TC
```suggestion
The `--server` flag in **traceectl** is used to specify the connection type that TraceeCtl should use to communicate with the Tracee server. This connection type can be either **Unix socket** or **TCP**.
```

2024-12-05 11:32 UTC, yanivagman commented on docs/docs/traceectl/index.md
> +**TraceeCtl** is a command-line interface (CLI) tool designed as a client service for [Tracee](https://github.com/aquasecurity/tracee), Aqua Security's open-source runtime security solution. Tracee p
```suggestion
**traceectl** is a command-line interface (CLI) tool designed as a client service for [Tracee](https://github.com/aquasecurity/tracee), Aqua Security's open-source runtime security solution. Tracee provides real-time, powerful observability for Linux environments by monitoring system calls, events, and more. TraceeCtl is built to simplify interactions with Tracee, making it easier for users to manage, monitor, and gather security insights.
```

2024-12-05 12:06 UTC, ShohamBit commented on cmd/traceectl/pkg/cmd/formatter/jsonFormat.go
I will delete this

2024-12-05 12:06 UTC, ShohamBit commented on cmd/traceectl/pkg/cmd/formatter/tableFormat.go
also

2024-12-05 12:13 UTC, ShohamBit commented on cmd/traceectl/cmd/event.go
> +		format.PrintJson(response.String())
fixed

2024-12-05 12:16 UTC, ShohamBit commented on cmd/traceectl/cmd/event.go
> +	if err := traceeClient.NewServiceClient(server); err != nil {
traceeClient is a struct that parse as a pointer to NewServiceClient function in client pkg, this will not work, please review the client pkg code

2024-12-05 12:16 UTC, ShohamBit commented on cmd/traceectl/cmd/event.go
> +	if err := traceeClient.NewServiceClient(server); err != nil {
ditto

2024-12-05 12:17 UTC, ShohamBit commented on cmd/traceectl/cmd/event.go
> +	if err := traceeClient.NewServiceClient(server); err != nil {
ditto

2024-12-05 12:19 UTC, ShohamBit commented on cmd/traceectl/cmd/root.go
> +	if err := traceeClient.NewDiagnosticClient(server); err != nil {
ditto

2024-12-05 12:20 UTC, ShohamBit commented on cmd/traceectl/cmd/root.go
> +	if err := traceeClient.NewServiceClient(server); err != nil {
ditto

2025-01-06 13:31 UTC, geyslan commented
I still need to generate some profiling data of the proctree. After that this will be the next to be reviewed. I din't forget it. 😄

2025-01-07 20:19 UTC, geyslan commented
Perhaps do you want to fix these before? https://github.com/aquasecurity/tracee/actions/runs/12221560791/job/35247793945?pr=4396#step:5:14

2025-01-10 12:41 UTC, geyslan requested changes
By running:

`sudo ./dist/tracee --grpc-listen-addr unix:/tmp/tracee.sock`
and
`sudo go run main.go stream --server /tmp/tracee.sock`

These are my current considerations, without diving into the code:

1. The table format should be fixed to print formatted, sized and padded columns:

@yanivagman should we bring Tracee table print logic into traceectl, or it should be built from ground up?

```
TIME            EVENT NAME POLICIES             PID             DATA      
11:04:20.943    security_socket_connect                      115863          Sockfd: 23, Type: SOCK_DGRAM, Remote_addr: unknown
11:04:20.943    security_inode_unlink                      115863          Pathname: /gg/.config/obsidian/Cache/Cache_Data/602073909c0e5ef2_0, Inode: 11410345, Dev: 271581186, Ctime: 1736511144436805063
11:04:21.466    security_inode_unlink                      115863          Pathname: /.org.chromium.Chromium.etVvra, Inode: 414968, Dev: 27, Ctime: 1736511155430523925
11:04:21.488    sched_process_exec                      2882348         Cmdpath: /usr/bin/docker, Pathname: /usr/bin/docker, Dev: 271581188, Inode: 14959315, Ctime: 1733226421039998680, Inode_mode: 33261, Interpreter_pathname: /usr/lib/ld-linux-x86-64.so.2, Interpreter_dev: 271581188, Interpreter_inode: 14953473, Interpreter_ctime: 1724352647074994761, Argv: docker, context, ls, --format, {{json .}}, Interp: /usr/bin/docker, Stdin_type: S_IFSOCK, Stdin_path: UNIX-STREAM, Invoked_from_kernel: 0, Prev_comm: code, Env: 
11:04:21.606    sched_process_exec                      2882358         Cmdpath: /bin/sh, Pathname: /usr/bin/bash, Dev: 271581188, Inode: 14942367, Ctime: 1728904355376515843, Inode_mode: 33261, Interpreter_pathname: /usr/lib/ld-linux-x86-64.so.2, Interpreter_dev: 271581188, Interpreter_inode: 14953473, Interpreter_ctime: 1724352647074994761, Argv: /bin/sh, -c, which ps, Interp: /bin/sh, Stdin_type: S_IFSOCK, Stdin_path: UNIX-STREAM, Invoked_from_kernel: 0, Prev_comm: code, Env: 
11:04:21.607    sched_process_exec                      2882358         Cmdpath: /usr/bin/which, Pathname: /usr/bin/which, Dev: 271581188, Inode: 14943707, Ctime: 1704474426940012677, Inode_mode: 33261, Interpreter_pathname: /usr/lib/ld-linux-x86-64.so.2, Interpreter_dev: 271581188, Interpreter_inode: 14953473, Interpreter_ctime: 1724352647074994761, Argv: which, ps, Interp: /usr/bin/which, Stdin_type: S_IFSOCK, Stdin_path: UNIX-STREAM, Invoked_from_kernel: 0, Prev_comm: sh, Env: 
11:04:21.610    sched_process_exec                      2882359         Cmdpath: /bin/sh, Pathname: /usr/bin/bash, Dev: 271581188, Inode: 14942367, Ctime: 1728904355376515843, Inode_mode: 33261, Interpreter_pathname: /usr/lib/ld-linux-x86-64.so.2, Interpreter_dev: 271581188, Interpreter_inode: 14953473, Interpreter_ctime: 1724352647074994761, Argv: /bin/sh, -c, /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=, Interp: /bin/sh, Stdin_type: S_IFSOCK, Stdin_path: UNIX-STREAM, Invoked_from_kernel: 0, Prev_comm: code, Env: 
11:04:21.611    sched_process_exec                      2882359         Cmdpath: /usr/bin/ps, Pathname: /usr/bin/ps, Dev: 271581188, Inode: 14943410, Ctime: 1715642853292467628, Inode_mode: 33261, Interpreter_pathname: /usr/lib/ld-linux-x86-64.so.2, Interpreter_dev: 271581188, Interpreter_inode: 14953473, Interpreter_ctime: 1724352647074994761, Argv: /usr/bin/ps, -ax, -o, pid=,ppid=,pcpu=,pmem=,command=, Interp: /usr/bin/ps, Stdin_type: S_IFSOCK, Stdin_path: UNIX-STREAM, Invoked_from_kernel: 0, Prev_comm: sh, Env: 
11:04:21.627    security_socket_connect                      2584510         Sockfd: 276, Type: SOCK_DGRAM, Remote_addr: unknown
```

2. After the above printed, it panicked:

```
Error receiving streamed event
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x86b067]

goroutine 1 [running]:
github.com/aquasecurity/tracee/cmd/traceectl/cmd.streamEvents(0xddd6e0, {0xc000156600, 0x0, 0x2})
        /home/gg/code/tracee/cmd/traceectl/cmd/stream.go:77 +0x427
github.com/aquasecurity/tracee/cmd/traceectl/cmd.init.func10(0xddd6e0?, {0xc000156600?, 0x4?, 0x97d1e9?})
        /home/gg/code/tracee/cmd/traceectl/cmd/stream.go:24 +0x18
github.com/spf13/cobra.(*Command).execute(0xddd6e0, {0xc0001565e0, 0x2, 0x2})
        /root/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:989 +0xa91
github.com/spf13/cobra.(*Command).ExecuteC(0xddce40)
        /root/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1117 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
        /root/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1041
github.com/aquasecurity/tracee/cmd/traceectl/cmd.Execute()
        /home/gg/code/tracee/cmd/traceectl/cmd/root.go:78 +0x1a
main.main()
        /home/gg/code/tracee/cmd/traceectl/main.go:9 +0xf
exit status 2
```

3. Running it without server flag make it attempts to connect to a predefined default path:

```
sudo go run main.go stream
Error calling Stream:  rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial unix /var/run/tracee.sock: connect: no such file or directory"
```

It's lacking error handling.

4. Output of `sudo go run main.go stream -h`

```
Stream Management:
Stream events directly from tracee to the preferred output format.

Usage:
  traceectl stream [policies...] [flags]

Flags:
  -f, --format string   Specify the output format for streamed events (json|table). Defaults to table. (default "table")
  -h, --help            help for stream

Global Flags:
  -o, --output string   Specify the output format
      --server string   Server connection path or address.
                                for unix socket <socket_path> (default: /tmp/tracee.sock)
                                for tcp <IP:Port> (default "/var/run/tracee.sock")
```

- What should the --output format flag change, since we already have the --format flag to choose it. Shouldn't it be a flag to write to any output specified independently of the format?
- If --server is not set, it should be default for only one single protocol/type. Perhaps it might have a parsing to check for "unix:sock.path" and "tcp:IP:port".

5. Create a Makefile

This will make the development process simpler regarding building, debugging, etc. You can mirror what we have in Tracee.

6. Squash commits of the same subject

This will help you to stack related changes in proper commits and the reviewers as well. In this PR I believe 2 or 3 commits will fit (1. for the new tool coming, 2. for doc changes, 3. for tests).

2025-03-24 12:12 UTC, NDStrahilevitz commented on mkdocs.yml
> +                - verion:  traceectl/commands/verion.md
Typo:
```suggestion
                - verion:  traceectl/commands/version.md
```

2025-03-24 12:47 UTC, NDStrahilevitz commented on cmd/traceectl/pkg/cmd/flags/policy.go
> +func PreparePolicy(policySlice []string) ([]string, error) {
This function results in the error when an empty policy input is passed (default or explicitly through `--policy \"\"`)

2025-03-24 12:48 UTC, NDStrahilevitz commented on docs/traceectl/commands/event.md
> +- **enable**: Enables capturing of a specific event type in Tracee.
This and disable result in a crash.

2025-03-24 12:49 UTC, NDStrahilevitz commented on cmd/traceectl/go.mod
> +module github.com/aquasecurity/tracee/cmd/traceectl
What's the reasoning for separating the compilation and module? Especially the compilation is rather inconvenient, it would be nice if you could add a proxy command in the main makefile (so `make traceectl` would be equivalent to `make -f cmd/traceectl/Makefile`). Maybe also copy in that command the binary to the main dist folder.

2025-03-25 14:27 UTC, ShohamBit commented on cmd/traceectl/cmd/stream.go
> +		return "unknown"
@NDStrahilevitz i think you review an old version of traceectl

2025-03-25 14:36 UTC, ShohamBit commented on docs/traceectl/commands/event.md
> +- **enable**: Enables capturing of a specific event type in Tracee.
can you please clarify a bit more about this section?

2025-03-25 14:36 UTC, NDStrahilevitz commented on cmd/traceectl/cmd/stream.go
> +func streamEvents(cmd *cobra.Command, args []string) {
still relevant in various parts of the code, just rename to `command`.

2025-03-25 14:39 UTC, ShohamBit commented on cmd/traceectl/go.mod
> +module github.com/aquasecurity/tracee/cmd/traceectl
as we discuss in earlier group meetings, we want the option of traceectl to a sapirt beating to, so it could compile and run without the need of the tracee code( only the binary is needed)

2025-03-25 14:47 UTC, NDStrahilevitz requested changes
First comment is critical.

2025-03-25 14:47 UTC, NDStrahilevitz commented on cmd/traceectl/pkg/cmd/stream.go
> +				if err != nil {
You must handle the `io.EOF` case separately
https://grpc.io/docs/languages/go/basics/

2025-03-25 14:47 UTC, NDStrahilevitz commented on docs/traceectl/commands/event.md
> +- **enable**: Enables capturing of a specific event type in Tracee.
When you run `traceectl events enable security_file_open` you get a panic and crash. Ditto for `disable`.

2025-03-26 09:39 UTC, NDStrahilevitz commented on cmd/traceectl/go.mod
> +module github.com/aquasecurity/tracee/cmd/traceectl
I think making compilation more easily accessible would be better. This doesn't mean removing the new Makefile, just adding a shortcut to it in the root makefile. 
Just to be sure, we plan to move traceectl to its own repository in the future?

2025-04-06 06:50 UTC, merged